"""init

Revision ID: 5fd24efa8cce
Revises: 431b4126ba53
Create Date: 2023-07-14 01:38:01.019951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd24efa8cce'
down_revision = '431b4126ba53'
branch_labels = None
depends_on = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    # Create  3 sample data for vaccine_tabl
    op.bulk_insert(
        sa.table('vaccine_table',
            sa.column('name', sa.String)
        ),
        [
            {'name': 'Pfizer'},
            {'name': 'Moderna'},
            {'name': 'AstraZeneca'}
        ]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
