name: Build, Deploy to DockerHub and Update to deployment repository

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hfte-auth:${{ github.run_number }} # NEEDS CHANGES HERE
          build-args: |
            "URL=${{ secrets.PROD_DB_URL }}"
            "SECRET_TOKEN=${{ secrets.PROD_SECRET_TOKEN  }}"

      - name: Alembic upgrade if there was changes in alembic directory
        id: alembic-upgrade
        if: ${{ steps.changed-files-alembic.outputs.any_changed == 'true' }}
        run: |
          echo -e "URL=${{ secrets.PROD_DB_URL }}\nSECRET_TOKEN==${{ secrets.PROD_SECRET_TOKEN }}" > ./app/.env
          alembic upgrade head
      - name: Checkout Deployment Repo
        uses: actions/checkout@v3
        with:
          repository: here-for-the-experience/deployment # NEEDS CHANGES HERE
          token: ${{secrets.PAT_TOKEN}}
      - name: Modify Deployment File
        run: |
          sed -i 's/hfte-app:.*/hfte-app:${{ github.run_number }}/g' environments/prod/app-1/deployment.yaml   # NEEDS CHANGES HERE

      - name: Push changes of deployment
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deployment update"
          git push https://$USERNAME:$REPO_KEY@github.com/here-for-the-experience/deployment.git # NEEDS CHANGES HERE
        env:
          REPO_KEY: ${{secrets.PAT_TOKEN}}
          USERNAME: github-actions[bot]

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
